### ISSUE TITLE
Define labels for `Deployment` (and other resources)

### ISSUE THREAD

**Issue by blakemorgan** [Twingate/kubernetes-operator#120]
**What is missing?**

There is no way to provide a value for `metadata.labels`.

**Why do we need it?**

To integrate with our observability tool (Datadog), we can add labels for auto-discovery of k8s resources. We can forward logs or metrics from the Twingate Operator to our Datadog tenant easily because we cannot add those labels.

**Environment**

* Twingate Kubernetes Operator version:

    `39d499d684694abd5df762834b7e6a57b81ed9fb`
    

**Anything else we need to know?**:

N/A

**Comment by ekampf** [comment]
Hey @blakemorgan !
Not sure what you mean by "and other resources" ?  Is the following PR answering your need?
https://github.com/Twingate/kubernetes-operator/pull/129

Or do you also want to be able to add label to the `Secret` object? `ServiceAccount`\roles too?
