### ISSUE TITLE
Define properties to facilitate HA deployment of the Twingate Operator

### ISSUE THREAD

**Issue by blakemorgan** [Twingate/kubernetes-operator#123]
**What is missing?**

There is no way for me to override the `replicas` property of the operator `Deployment` or the `topologySpreadConstraints` of its. There is also no `podDisruptionBudget` created for the operator's pods. 

**Why do we need it?**

Even though the Twingate Operator `Deployment` has a very small footprint and is quick to restart, we'd prefer to run >= 2 pods at a time and with topology spread constraints to attempt to schedule pods in different availability zones. Doing this minimizes the amount of downtime the operator would have due to outside factors. 

Also, when updating the Twingate Operator `Deployment`, since it's only running a single replica and has no pod disruption budget, the new pod is started in place of the old one causing a brief moment of downtime for the `Deployment`.

It would be nice if high-availability was added by default to the `Deployment` by defining a `replicas` value >1 and including a `PodDisruptionBudget` by default. Leaving it as is would also be fine so long as it was possible for users of the Helm chart to pass in their own # of replicas, topology spread constraints, and PDB.

**Environment**

* Twingate Kubernetes Operator version:

    `39d499d684694abd5df762834b7e6a57b81ed9fb`
    

**Anything else we need to know?**:

N/A

**Comment by ekampf** [comment]
Hey @blakemorgan
As the operator only syncs information between your cluster objects and Twingate when it restarts it just means a short delay in that sync - and only if something actually changed that requires a sync.
For example, if you deploy a new `TwingateResource` right when the operator is down - it will only pick it up when its back up.
Normally thoough, when system is already in sync and operator restarts or goes down - nothing happens.

Running multiple operators requires them to now sync among themselves (there's a new `TwingateResource` object and 2 operator pods are running - who syncs it?) which brings a host of new edge cases to think about and handle.
I'm not sure the added complexity adds enough value to be worth tackling?

**Comment by ekampf** [comment]
Adding a `PodDistruptionBudget` is interesting though... 
Should we just hardcode it and set `maxUnavailable: 1` or do you think we should allow some customizations via `values.yaml` ?

**Comment by blakemorgan** [comment]
Makes sense -- probably overkill in this case.
