### ISSUE TITLE
Unsupported CRD fields for Kubernetes < 1.25

### ISSUE THREAD

**Issue by blakemorgan** [Twingate/kubernetes-operator#124]
**What happened?**

The README for this operator says it supports Kubernetes 1.16+, but the CRDs it creates `CustomResourceValidationExpressions` (using `x-kubernetes-validations`) which was Alpha and disabled by default in k8s 1.23-1.24, then enabled by default in k8s 1.25.

Additionally, the `nullable: false` field is removed from the properties the CRD defines when its applied to the cluster.

We are using Argo CD to deploy the Twingate Operator and its running on Kubernetes 1.24 (with the `CustomResourceValidationExpressions` disabled by default). After deploying the Helm chart, we can see the drift in each of the CRDs. See screenshots for examples (the left is what's live on the cluster, the right is what the Helm chart defines).

_TwingateConnectors_
<img width="1464" alt="Screenshot 2024-02-07 at 1 32 12 PM" src="https://github.com/Twingate/kubernetes-operator/assets/9389424/56bdb39d-26b3-4d2e-a28e-67296eac378f">

_TwingateResourceAccesses_
<img width="1463" alt="Screenshot 2024-02-07 at 1 32 54 PM" src="https://github.com/Twingate/kubernetes-operator/assets/9389424/2c8c0125-4f85-41cd-a228-5d3563280c4b">

_TwingateResources_
<img width="1493" alt="Screenshot 2024-02-07 at 1 33 29 PM" src="https://github.com/Twingate/kubernetes-operator/assets/9389424/c0394a5f-1e5d-471b-b779-28516a34fd46">

**Did you expect to see something different?**

The expected behavior is to only render the `x-kubernetes-validations` fields in the Helm chart if the `CustomResourceValidationExpressions` is enabled in the cluster (if running v1.23 or v1.24) or if running 1.25+.

It's also expected that the `nullable` fields aren't rendered in the CRDs generated by the Helm chart if they would get removed when applied to the cluster. I tried to investigate why this behavior was happening in the first place, but didn't find a solid solution. My hunch is it may be due to how different versions of k8s renders the CRD and was thinking that removing `nullable: false` and adding the property to the `required` list may work instead (though that's conjecture -- I haven't tested that behavior)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a k8s cluster running v1.24 and don't enable the `CustomResourceValidationExpressions` feature gate (it should be disabled by default)
2. Deploy the Twingate Operator
3. Compare the YAML of CRDs running on the cluster to the CRDs generated by the Helm chart.

**Environment**

* Twingate Kubernetes Operator version:

    `39d499d684694abd5df762834b7e6a57b81ed9fb`
    

* Kubernetes version information:

    `v1.24.17-eks-5e0fdde`
    

* Kubernetes cluster kind:

    EKS with managed node groups

* Manifests:

That's a lot of YAML to include here. The screenshots above should help, but if you still want the manifests feel free to Slack me and I can send them your way.

* Twingate Kubernetes Operator Logs:

N/A. There was nothing in the logs related to this behavior.

**Anything else we need to know?**:

I don't know if this would have an effect on me creating the `TwingateConnector`, `TwingateResourceAccess`, or `TwingateResource` resources -- I haven't tried doing that yet. All I've tried is deploying the operator.

**Comment by ekampf** [comment]
CRDs are not a helm template so not sure how I can configure waht they emit based on the version you deploy to.
Not sure its the right thing to do either (haven't found any other chart that does this)
Can't you customize Argo's diffing algorithm to ignore these specific drifts? 
(this maybe? https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration)

**Comment by blakemorgan** [comment]
Ah yes good point -- templating CRDs isn't supported. Yes we can ignore the diff, just wanted to ask here first. Thanks for the response!
