### ISSUE TITLE
Explicit deny when defining a protocol

### ISSUE THREAD

**Issue by blakemorgan** [Twingate/kubernetes-operator#195]
**What is missing?**

When I create a new `TwingateResource`, I can explicitly deny access to TCP or UDP and it's enabled by default. I looked at the CRDs and only see `ALLOW_ALL` and `RESTRICTED` (with with `RESTRICTED`, I have to define ports). I wish there was a `DENY_ALL` option for protocols. 

**Why do we need it?**

When we create new Twingate resources, we explicitly deny all access except the ports we expect to minimize a potential attack surface.

**Environment**

* Twingate Kubernetes Operator version:

    `v0.6.1`

**Comment by arthur-leclerc** [comment]
I was in the same situation as you, version `0.6.2` allows you to block all ports by specifying a `RESTRICTED` policy with an empty port array. The behavior is slightly different from the Terraform provider, which [has an additional `DENY_ALL` policy](https://registry.terraform.io/providers/Twingate/twingate/latest/docs/resources/resource#policy).

Version `0.6.1` had a bug (#192) that prevents using `RESTRICTED` with an empty array.
