### ISSUE TITLE
Missing misconfiguration information in connector resource

### ISSUE THREAD

**Issue by cehoffman** [Twingate/kubernetes-operator#214]
**What happened?**

Applying a connector resource with a bad image repository doesn't surface the misconfiguration in the status. Instead it surfaces an error trying to get the pod.

**Did you expect to see something different?**

Expected to see the error from the operator that the image repository was invalid.

**How to reproduce it (as minimally and precisely as possible)**:

Apply a connector resource like this:

```yaml
apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: sly-platapus
spec:
  imagePolicy:
    provider: google
    schedule: 0 0 * * *
```

It was expected that the google provider meant the operator would automatically default to a google registry instead of keeping the default docker hub one.

**Environment**

* Twingate Kubernetes Operator version:

    `v0.6.2`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8-gke.1067004", GitCommit:"6f460c12ad45abb234c18ec4f0ea335a1203c415", GitTreeState:"clean", BuildDate:"2024-01-04T22:48:32Z", GoVersion:"go1.20.11 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
`
    

* Kubernetes cluster kind:

GKE

* Manifests:

```
insert manifests relevant to the issue
```

* Twingate Kubernetes Operator Logs:

```
insert Twingate Kubernetes Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by ekampf** [comment]
@cehoffman th operator has no way of validating the image information - it trusts Kubernetes with that logic.
How would you like to see it on the `TwingateConnector` object?

> It was expected that the google provider meant the operator would automatically default to a google registry 

Google does not have a "global" container registry AFAIK...  Only per GCP project.
This feature is meant for companies who, for extra security, only allow their GKE cluster to fetch images from their project's repository and they proxy or manually copy external images there.

**Comment by cehoffman** [comment]
What I expect is that the resource is rejected at creation if the provider is google but no registry is also given since it is guaranteed to not work. My initial expectation though was setting the Google provider would have the operator default the registry to a Twingate managed copy of the docker registry but within GCP. I wanted to do that to limit exposing us to docker hub availability since we are on GCP. The think was this was an easy first step to that problem withou fully mirroring images in our GCP artifact registry.

**Comment by ekampf** [comment]
I see...  makes sense, I'll try to add that validation rule to the CRD
