### ISSUE TITLE
Make connector `containerExtra` mutable

### ISSUE THREAD

**Issue by cehoffman** [Twingate/kubernetes-operator#215]
**What is missing?**

Once the `containerExtra` object is set, it can not be altered. I don't have a good reason I see to make it immutable and it makes updating it painful since it requires a full resource delete and create again.

**Why do we need it?**

Lacking any example documentation on the field, I resorted to trial and error to get the desired result. The immutable aspect makes that process cumbersome and frankly annoying.

**Environment**

* Twingate Kubernetes Operator version:

    `0.6.2`
    

**Anything else we need to know?**:

I'm resorting to this because I want to enable the log analytics. It would be nice for this to be a first class config option for the resource.

**Comment by ekampf** [comment]
Agree.
Will work on this ASAP
