### ISSUE TITLE
Set environment variables in containerExtra breaks deployment

### ISSUE THREAD

**Issue by cehoffman** [Twingate/kubernetes-operator#216]
**What happened?**

Setting `containerExtra` with an `env` variable results in all necessary environment variables to configure the connector set by the operator to be removed.

**Did you expect to see something different?**

I expected the `containerExtra` to be added to the container, not replace.

**How to reproduce it (as minimally and precisely as possible)**:

Add

```yaml
spec:
  containerExtra:
    env:
      - name: TEST
        value: breaks
```

**Environment**

* Twingate Kubernetes Operator version:

    `0.6.2`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8-gke.1067004", GitCommit:"6f460c12ad45abb234c18ec4f0ea335a1203c415", GitTreeState:"clean", BuildDate:"2024-01-04T22:48:32Z", GoVersion:"go1.20.11 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
`
    

* Kubernetes cluster kind:

  GKE
* Manifests:

```
insert manifests relevant to the issue
```

* Twingate Kubernetes Operator Logs:

```
insert Twingate Kubernetes Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by ekampf** [comment]
Releasing `0.6.3` with this fix
