### ISSUE TITLE
Connector pod annotation configuration

### ISSUE THREAD

**Issue by cehoffman** [Twingate/kubernetes-operator#217]
**What is missing?**

Ability to set pod annotations on the create pod for a connetor.

**Why do we need it?**

For Datadog log monitoring, we need to configure the agent using annotations on the pod.

**Environment**

* Twingate Kubernetes Operator version:

    `0.6.2`
    

**Anything else we need to know?**:

**Comment by ekampf** [comment]
Agree. Will add ASAP

**Comment by ekampf** [comment]
@cehoffman  can you use `labels` too?   currently `TwingateConnector` labels will be copied to the pod too...
