### ISSUE TITLE
Publish versioned chart

### ISSUE THREAD

**Issue by cehoffman** [Twingate/kubernetes-operator#226]
**What is missing?**

A native helm way of installing the chart without cloning the git repository.

**Why do we need it?**

To integrate with our deployment pipeline, we have to setup a extra pre process that pulls the git repository to extract the helm chart for use in the remaining parts of our pipeline.

**Environment**

* Twingate Kubernetes Operator version:

    `0.6.2
    

**Anything else we need to know?**:

Publishing this through GitHub packages should be fine, but we haven't use that explicitly. We've used the GitHub pages method of publishing the chart many times though.

**Comment by ekampf** [comment]
Yep. Definately something we need to do but not so simple so might take some time...

**Comment by svyatoslavmo** [comment]
@ekampf any ETA on this one? It would provide easier deployment path

**Comment by ekampf** [comment]
@svyatoslavmo  no ETA I can share yet but it is at the top of my list

**Comment by ekampf** [comment]
@svyatoslavmo would love some feedback on https://github.com/Twingate/kubernetes-operator/pull/265
Publishing to an OCI repo on github solves answers your needs right?

**Comment by svyatoslavmo** [comment]
Yes, thank you! @ekampf 
I would also suggest to version Helm chart and operator together, as Grafana does.

**Comment by ekampf** [comment]
@svyatoslavmo isnt the reason Helm chart has `version` and `appVersion` as separate properties is to avoid this?
Helm chart rarely changes do we really want to update its version with every release?

**Comment by svyatoslavmo** [comment]
Yes, because it's one version for all changes. Your end user will bump just the chart version, regardless what's been changed. 
[check this out](https://github.com/grafana/helm-charts/commit/c946bbc836b6c5748326dd6d2f09a7a8ef4a8517)

**Comment by ekampf** [comment]
I see...    ok will make it work on https://github.com/Twingate/kubernetes-operator/pull/265

**Comment by cehoffman** [comment]
I'm ok with either method in general, but for the way my company currently manages these type of resources moving the chart version in lock step with the application version is easiest.

**Comment by AlexisDaciuk** [comment]
Any updates on this? we are using the Operator in our clusters but it's not great to have to install it by hand

**Comment by AlexisDaciuk** [comment]
bump

**Comment by ekampf** [comment]
@AlexisDaciuk sorry it has been taking so long... PR is almost ready at https://github.com/Twingate/kubernetes-operator/pull/479

**Comment by ekampf** [comment]
@HaddadJoe PR is merged and new operator released 😃
