### ISSUE TITLE
Add ability to specify labels for pods created by TwingateConnector

### ISSUE THREAD

**Issue by joshuabaird** [Twingate/kubernetes-operator#228]
**What is missing?**
We would like the ability to add labels to pods created by the _TwingateConnector_ CRD.  The operator already provides the ability to create annotations on these pods, but not labels.

**Why do we need it?**
We need to add custom labels to our pods to influence the way they are scheduled on our cluster.

**Environment**

* Twingate Kubernetes Operator version:

0.7.0

**Comment by ekampf** [comment]
Hey @joshuabaird 
The pod labels derived from the `TwingateConnector` object - whatever labels you put on it will also propagate to the pod

**Comment by ekampf** [comment]
@joshuabaird closing this issue feel free to reopen if its still an issue
