### ISSUE TITLE
Ability to set labels on connector pod

### ISSUE THREAD

**Issue by cehoffman** [Twingate/kubernetes-operator#264]
**What is missing?**

Ability to set specific labels on the resulting connector pod.

**Why do we need it?**

Specifically labels on the pod enable targeting the pod from other resources. Our use case is setting anti affinity rules to prevent two connectors for the same network from running on the same node. This is to prevent node failure or drain from interrupting all connector availability simultaneously.

**Environment**

GKE 1.27

* Twingate Kubernetes Operator version:

    `0.10.0`
    

**Anything else we need to know?**:

**Comment by ekampf** [comment]
@cehoffman labels you add to the `TwingateConnector` object will also propogate to the Pod it creates.
Is that good enough or are you looking to set labels explicitly just on the Pod?
