### ISSUE TITLE
Using the Operator with annotations have some problems

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate/kubernetes-operator#269]
Hi
I use the newest operator and try to create resources with annotations.
At first, I added the: `twingate.com/resource: 'true'` annotation and got:

> cannot patch resource "services/status" in API group "" in the namespace "namespace"', 'reason': 'Forbidden'

So I added `services/status` manually to the clusterRole.

Then I got:

>  cannot create resource \"twingateresources\" in API group \"twingate.com\" in the namespace \"namespace\"","reason":"Forbidden"  

So I added 'create' manually to the clusterRole.

Then the resource was created.
Alias works fine.

When I tried to add isVisible annotation, I got:

> spec.isVisible: Invalid value: \\\\\\"string\\\\\\": spec.isVisible in body must be of type boolean

but k8s doesn't let you enter a non-string value in annotations. Both "False" and "false" didn't work.

Please kindly fix it.
Thanks!

**Comment by ekampf** [comment]
Thanks @ErezWeiss !
Pushed a fix and will release `0.10.1` ASAP

**Comment by ekampf** [comment]
@ErezWeiss FYI `0.10.1` is out

**Comment by ErezWeiss** [comment]
@ekampf Thanks!!
