### ISSUE TITLE
Add a resource to a group using annotations

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate/kubernetes-operator#271]
Hi guys!
Please add the ability to add a resource to a group using annotations.
Something like:
`twingate.com/resourceaccess-principalId: '{GROUP-ID}'
`

Thanks!

**Comment by ErezWeiss** [comment]
Adding the option to import existing resources, as adding twingate.com/resource-id doesn't work.

**Comment by ErezWeiss** [comment]
also adding twingate.com/resource-name doesn't change the resource name.

**Comment by ErezWeiss** [comment]
also removing the annotation doesn't delete the resource.

**Comment by ekampf** [comment]
1. Importing existing resources while using annotations - didnt think of that feature. Will think about adding it (there's no support for `twingate.com/resource-id `) today
2. Should work... will add an integration test and fix if necessary
3. Will look into it ASAP

**Comment by ekampf** [comment]
@ErezWeiss please see docs: https://github.com/Twingate/kubernetes-operator/wiki/User-Guide#exposing-a-cluster-workload-by-annotating-an-existing-service

Only the following annotations are supported at the moment:
- `twingate.com/resource-alias`
- `twingate.com/resource-isBrowserShortcutEnabled`
- `twingate.com/resource-securityPolicyId`
- `twingate.com/resource-isVisible`

I understand the use case for adding `id` for importing.
Is customizing the `name` really necessary?

**Comment by ekampf** [comment]
I've been thinking more about 1 - adding a `twingate.com/resource-id` annotation to support import, or `twingate.com/resource-principalIds` (has to be plural - you could want to add a resource to multiple principals) seems to me like an abuse of service annotations for advanced use cases that better fit using `TwingateResource` and `TwingateResourceAccess` directly...

**Comment by ekampf** [comment]
@ErezWeiss name annotation (`twingate.com/resource-name`) supported in version `0.11.0` so you can use it.
I will close this issue for now but love the feedback keep it coming :)
