### ISSUE TITLE
Since last fix, take a long time for Operator to update resource access

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate/kubernetes-operator#281]
https://github.com/Twingate/kubernetes-operator/commit/c1645f4a9a5aa43e26ac7ecbe0a2f0a6d0743bc8#commitcomment-141838129

Since this fix, we have to wait long until Twingate access is updated.
@ekampf

**Comment by ekampf** [comment]
Thats odd because we still trigger sync on `TwingateResourceAccess.spec` updates:
```
kopf.on.update("twingateresourceaccess", field="spec")(twingate_resource_access_sync)
```

Can you give more details on the changes you're making?

**Comment by ekampf** [comment]
I found the issue...

**Comment by ekampf** [comment]
`0.11.2.` is releasing

**Comment by ErezWeiss** [comment]
Thanks!!!
