### ISSUE TITLE
Using the helm chart, logVerbosity: "verbose" prints also DEBUG logs

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate/kubernetes-operator#286]
We are using v0.11.2 helm cahrt.
We see the logs print DEBUG logs, even when logVerbosity set to "verbose".
Thanks :)

**Comment by ekampf** [comment]
This is the defined behavior per [kopf](https://github.com/nolar/kopf/blob/main/kopf/_core/actions/loggers.py#L179)
Basically the difference between `debug` and `verbose` is just wether `asuncio` logs or not.

Will keep this issue open as we'll probably want to add more options to logging...

**Comment by ErezWeiss** [comment]
I see
here: https://github.com/Twingate/kubernetes-operator/blob/main/deploy/twingate-operator/values.yaml I can see logVerbosity: "quiet|verbose|debug", so there is no INFO or WARNING available?
