### ISSUE TITLE
ownerReferences of TwingateResourceAccess prevents ArgoCD from deleting it

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate/kubernetes-operator#287]
Using v0.11.2. We are using ArgoCD to create both TwingateResource and TwingateResourceAccess.

When I delete a TwingateResourceAccess from the source code, that what I see in Argo:
<img width="751" alt="twingatepic" src="https://github.com/Twingate/kubernetes-operator/assets/35471632/a81ef95a-fe91-46ce-b3fc-46657d147604">
The resource on the right (baseline-analyzer-developers-access) was before the deletion like other resources (baseline-analyzer-admins-access for instance).
Once we delete it, ArgoCD refuse to delete it as it has the ownerReferences field, that connects it to the resource.
Once we delete the ownerReferences field, the resource is deleted.

I came across this: https://github.com/argoproj/argo-cd/issues/4764
It may help...
Thanks!

**Comment by ekampf** [comment]
We initially added this so that if you delete a resource its access object get deleted too.
I wonder if we should just skip this...

**Comment by ErezWeiss** [comment]
> We initially added this so that if you delete a resource its access object get deleted too. I wonder if we should just skip this...

Maybe this logic should be Operator-wise and not K8S-wise.
@ekampf

**Comment by ekampf** [comment]
You might be right.

Giving it a second thought I'd expect that if the references `TwingateResource` is deleted, the access object sill remains on k8s just starts logging errors in reconciliation...
