### ISSUE TITLE
Toleration / Node Selector support for TwingateConnector resources?

### ISSUE THREAD

**Issue by zvickery** [Twingate/kubernetes-operator#338]
**What happened?**
It would be nice if the connector pods created by the operator could be specified with tolerations and node selectors.  Looking at the CRD, this doesn't seem possible currently.  Am I missing something or would this be a new feature?

**Did you expect to see something different?**
Was hoping the pods created by the operator could be constrained the same way the operator itself can be.

**How to reproduce it (as minimally and precisely as possible)**:
Any `TwingateConnector` resource will create connector pods with no node selector and default tolerations.

**Environment**

* Twingate Kubernetes Operator version:

    `0.11.3`

* Kubernetes version information:

    `Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1-eks-1de2ab1`

* Kubernetes cluster kind:
   EKS via terraform

* Manifests:

```- apiVersion: twingate.com/v1beta
  kind: TwingateConnector
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"twingate.com/v1beta","kind":"TwingateConnector","metadata":{"annotations":{},"name":"REDACTED","namespace":"twingate"},"spec":{"imagePolicy":{"provider":"dockerhub","schedule":"0 15 5 * *"},"name":"REDACTED"}}
      twingate.com/kopf-managed: "yes"
      twingate.com/last-handled-configuration: |
        {"spec":{"hasStatusNotificationsEnabled":true,"id":"REDACTED","imagePolicy":{"allowPrerelease":false,"provider":"dockerhub","repository":"twingate/connector","schedule":"0 15 5 * *"},"logAnalytics":true,"logLevel":3,"name":"REDACTED"}}
      twingate.com/last-version-check: "2024-06-11T23:29:00Z"
      twingate.com/next-version-check: "2024-07-05T15:00:00Z"
    creationTimestamp: "2024-06-11T23:28:43Z"
    finalizers:
    - twingate.com/finalizer
    generation: 272905
    name: REDACTED
    namespace: twingate
    resourceVersion: "REDACTED"
    uid: REDACTED
  spec:
    hasStatusNotificationsEnabled: true
    id: REDACTED
    imagePolicy:
      allowPrerelease: false
      provider: dockerhub
      repository: twingate/connector
      schedule: 0 15 5 * *
    logAnalytics: true
    logLevel: 3
    name: REDACTED
  status:
    twingate_connector_create:
      success: true
      ts: 2024-06-11T23:28:44.502471
      twingate_id: REDACTED
    twingate_connector_pod_reconciler:
      success: true
      ts: 2024-06-27T21:51:03.519140
    twingate_connector_update/spec:
      message: No update required
      success: true
      ts: 2024-06-11T23:28:44.616950
      twingate_id: REDACTED
kind: List
metadata:
  resourceVersion: ""
```

* Twingate Kubernetes Operator Logs:

   N/A

**Anything else we need to know?**:

N/A

**Comment by ekampf** [comment]
Hey @zvickery !
This is supported via the `TwingateConnector.spec.podExtra` field - you can specify there whatever extra stuff you want to add to the pod definition (toleration, nodeSelector, etc.)

https://github.com/Twingate/kubernetes-operator/wiki/API-Reference#twingateconnectorspec

**Comment by zvickery** [comment]
Thank you!  It works great!
