### ISSUE TITLE
twingate/connector print version

### ISSUE THREAD

**Issue by yene** [Twingate/kubernetes-operator#481]
**What is missing?**
twingate/connector should print version during startup. 

**Why do we need it?**
Some tooling only displays the container hash which makes hard for admins to figure out the version.

**Environment**
the cloud

* Twingate Kubernetes Operator version:

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:
we are a customer

**Comment by ekampf** [comment]
This is actually a `connector` feature and not an operator one...  will forward to that team

**Comment by yene** [comment]
@ekampf where do I report bugs, we just deployed connector 70+ and DNS broke etc
It feels like my company will create a lot of reports

**Comment by ekampf** [comment]
@yene so connector actually already does this, if you look at the log and `grep` for "sdwan_new" you should see a line looking like this where `app_version` is the connector version.
```
[INFO] [libsdwan] sdwan_new: libsdwan_version=0.166.1, app_version=1.73.0, platform=Linux-x86_64
```

Re opening support tickets the details are here: https://www.twingate.com/docs/support
