### ISSUE TITLE
I need metric settings for network

### ISSUE THREAD

**Issue by Jesus-is-a-good-God** [Twingate/kubernetes-operator#495]
On my Linux Mint 22 I could no longer access local devices when Twingate was running. The problem was that Linux Mint assigns a metric of 100 by default for local interfaces and Twingate 25. This meant that the Twingate interface had a higher priority than the local one and network requests that were in the local network were sent out via the Twingate interface, which is why they were not found. I adapted the Linux Mint interface because I couldn't find an option to do this in Twingate.

I would like an option to change this, for example via the policies in Webconsol.

**Comment by ekampf** [comment]
Hey @Jesus-is-a-good-God - this does not seem like a Kubernetes Operator question or issue.
For general technical help with Twingate please refer to https://www.twingate.com/docs/support
